syntax = "proto3";
package discovery;

import "gogoproto/gogo.proto";
import "rustproto.proto";

option (gogoproto.sizer_all) = true;
option (gogoproto.marshaler_all) = true;
option (gogoproto.unmarshaler_all) = true;
option (rustproto.lite_runtime_all) = true;

option java_package = "org.tikv.kvproto";

service Discovery {
	rpc Register(RegisterRequest) returns (RegisterResponse) {};

	rpc Deregister(DeregisterRequest) returns (DeregisterResponse) {};

	rpc Campaign(CampaignRequest) returns (CampaignResponse) {};

	rpc KeepAlive(KeepAliveRequest) returns (KeepAliveResponse) {};

	rpc GetServiceEndpoint(GetServiceEndpointRequest) returns (GetServiceEndpointResponse) {};

	rpc GetAllServiceEndpoints(GetAllServiceEndpointsRequest) returns (GetAllServiceEndpointsResponse) {};
}

message RegisterRequest {
	string service_name = 1;
	string endpoint = 2;
}

message RegisterResponse {
	Error error = 1;
}

message DeregisterRequest {
	string service_name = 1;
	string endpoint = 2;
}

message DeregisterResponse {
	Error error = 1;
}

message CampaignRequest {
	string service_name = 1;
	string endpoint = 2;
}

message CampaignResponse {
	Error error = 1;
}

message KeepAliveRequest {
	string service_name = 1;
	string endpoint = 2;
}

message KeepAliveResponse {
	Error error = 1;
}

message GetServiceEndpointRequest {
	string service_name = 1;
}

message GetServiceEndpointResponse {
	Error error = 1;
	string endpoint = 2;
}

message GetAllServiceEndpointsRequest {
	string service_name = 1;
}

message GetAllServiceEndpointsResponse {
	Error error = 1;
	repeated string endpoints = 2;
}

message Error {
    string message = 1;
}